services:
  apache-drill:
    image: apache/drill:1.22.0
    container_name: ${DRILL}
    stdin_open: true
    tty: true
    ports:
      - ${DRILL_PORT}:8047
      - 31011:31010
    restart: unless-stopped
 
  superset-db:
    image: postgres:16
    container_name: ${POSTGRES}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /app/superset/${POSTGRES}:/var/lib/postgresql/data
    restart: unless-stopped
 
  superset-init:
    image: superset:compose
    container_name: ${SUPERSET_INIT}
    depends_on:
      - superset-db
    environment:
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@superset-db:5432/${DB_NAME}"
    command: >
      /bin/bash -lc "
      set -e;
      until (echo > /dev/tcp/superset-db/5432) >/dev/null 2>&1; do
        echo 'waiting postgres...'; sleep 2;
      done;
      /app/env/bin/superset db upgrade;
      /app/env/bin/superset fab create-admin --username admin --firstname Admin --lastname User --email admin@local --password admin || true;
      /app/env/bin/superset init;
      "
    restart: "no"

  superset:
    image: superset:compose
    container_name: ${SUPERSET_WEB}
    depends_on:
      - superset-db
      - superset-init
    ports:
      - ${SUPERSET_WEB_PORT}:8088
    environment:
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@superset-db:5432/${DB_NAME}"

    command: ["superset", "run", "-p", "8088", "-h", "0.0.0.0"]
    restart: unless-stopped