apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superset
  template:
    metadata:
      labels:
        app: superset
    spec:
      containers:
      - name: superset
        image: debian-superset:5.0.1
        imagePullPolicy: Never
        ports:
        - containerPort: 8088

---
apiVersion: v1
kind: Service
metadata:
  name: superset-service
spec:
  type: NodePort
  selector:
    app: superset
  ports:
    - name: http
      port: 8088
      targetPort: 8088
      nodePort: 30088
