services: 
  postgres-server-01:
    image: postgres:16
    container_name: postgres-server-01
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - /app/dbForTest/postgres-server-01:/var/lib/postgresql/data
    restart: unless-stopped